// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import DropdownController from "./dropdown_controller"
application.register("dropdown", DropdownController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import StockInfoApiController from "./stock_info_api_controller"
application.register("stock-info-api", StockInfoApiController)

import StockPageController from "./stock_page_controller"
application.register("stock-page", StockPageController)

import TimescrollController from "./timescroll_controller"
application.register("timescroll", TimescrollController)

import TwitterController from "./twitter_controller"
application.register("twitter", TwitterController)

import YahooapiController from "./yahooapi_controller"
application.register("yahooapi", YahooapiController)
